name: speech_text
on: [push]
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train_model.ipynb
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          echo "## Data viz" >> report.md
          cml-publish model_1.png --md >> report.md
          
          

